[
	"Afternoon",
	"Afternoon, {name}",
	"Back at it!",
	"Back at it, {name}",
	"Coffee and Clepsydra time?",
	"Evening",
	"Evening, {name}",
	"Golden hour thinking",
	"Good afternoon",
	"Good afternoon, {name}",
	"Good evening",
	"Good evening, {name}",
	"Good morning",
	"Greetings, whoever you are",
	"Happy Friday",
	"Happy Friday, {name}",
	"Happy Monday",
	"Happy Monday, {name}",
	"Happy Saturday!",
	"Happy Saturday, {name}",
	"Happy Sunday",
	"Happy Sunday, {name}",
	"Happy Thursday",
	"Happy Thursday, {name}",
	"Happy Tuesday",
	"Happy Tuesday, {name}",
	"Happy Wednesday",
	"Happy Wednesday, {name}",
	"Hello, night owl",
	"Hey there",
	"Hey there, {name}",
	"It's late-night {name}",
	"It's late-night",
	"Let’s chat incognito",
	"Moonlit chat?",
	"Sunday session, {name}?",
	"Sunday session?",
	"Welcome to the weekend",
	"Welcome to the weekend, {name}",
	"Welcome",
	"Welcome, {name}",
	"{name} returns!",
];
// "A greeting for the user — please try to find an idiomatic greeting that would sound natural to a native speaker. This greeting should be appropriate in the late night"
// "A greeting for the user — please try to find an idiomatic greeting that would sound natural to a native speaker. This greeting should be appropriate in the morning"
