import { createEditor, Editor, Node, Transforms } from "slate";
import { describe, expect, it } from "vitest";
import { withSchema } from "#/editor/schema/withSchema";
import { markdownToSlate, slateToMarkdown } from "../index";

const REGION_ID = "f64aa934-60f8-4e74-8760-12b7e515f6ef";
const HEADER = `<!-- clep:generated\nversion = 1\nid = "${REGION_ID}"\nbase = "tastings"\ntemplate = "beer-notes"\noutput_hash = "blake3:${"a".repeat(64)}"\n-->`;
const END = "<!-- /clep:generated -->";

describe("generated-region Markdown conversion", () => {
  it("retains exact generated bytes when handwritten prose is edited", () => {
    const payload =
      "\r\n\r\n# Beer &amp; hops\r\n\r\nA  tasting.  \r\n\tExtra whitespace.\r\n\r\n";
    const region = `${HEADER}${payload}${END}`;
    const editor = createEditor();
    editor.children = markdownToSlate(`Before.\n\n${region}\n\nAfter.\n`);

    Transforms.insertText(editor, "Updated ", {
      at: { path: [0, 0], offset: 0 },
    });

    expect(slateToMarkdown(editor.children)).toBe(
      `Updated Before.\n\n${region}\n\nAfter.\n`,
    );
  });

  it("preserves malformed markers without consuming the intervening prose", () => {
    const malformedEnd = "<!-- /clep:generated broken -->";
    const editor = createEditor();
    editor.children = markdownToSlate(
      `${HEADER}\n\nHandwritten.\n\n${malformedEnd}\n\nAfter.\n`,
    );
    expect(editor.children[0]).toMatchObject({
      type: "generated-region",
      status: "invalid",
    });
    Transforms.insertText(editor, "Still editable. ", {
      at: { path: [1, 0], offset: 0 },
    });
    expect(slateToMarkdown(editor.children)).toBe(
      `${HEADER}\n\nStill editable. Handwritten.\n\n${malformedEnd}\n\nAfter.\n`,
    );
  });

  it("leaves prose after an unterminated HTML header editable", () => {
    const brokenHeader = '<!-- clep:generated\nversion = 1\nbase = "tastings"';
    const editor = createEditor();
    editor.children = markdownToSlate(`${brokenHeader}\n\nHandwritten.\n`);
    Transforms.insertText(editor, "Updated ", {
      at: { path: [1, 0], offset: 0 },
    });
    expect(slateToMarkdown(editor.children)).toBe(
      `${brokenHeader}\n\nUpdated Handwritten.\n`,
    );
  });

  it("makes both copies of a duplicated region non-addressable without losing source", () => {
    const first = `${HEADER}\n\nFirst &amp; untouched.\n\n${END}`;
    const second = `${HEADER}\n\nSecond  untouched.\n\n${END}`;
    const source = `${first}\n\n${second}\n`;
    const nodes = markdownToSlate(source);
    expect(nodes).toMatchObject([
      { type: "generated-region", status: "invalid" },
      { type: "generated-region", status: "invalid" },
    ]);
    expect(slateToMarkdown(nodes)).toBe(source);
  });

  it("retains nested regions as non-addressable repair source", () => {
    const innerHeader = HEADER.replace(
      REGION_ID,
      "d1e4e73f-4414-4b83-bd28-0bd1aed1220c",
    );
    const source = `${HEADER}\n\nOuter &amp;  prose.\n\n${innerHeader}\n\nInner.\n\n${END}\n\n${END}\n`;
    const nodes = markdownToSlate(source);
    expect(nodes).toMatchObject([
      { type: "generated-region", status: "invalid" },
    ]);
    expect(slateToMarkdown(nodes)).toBe(source);
  });

  it("keeps fenced and indented marker examples inert beside an active region", () => {
    const region = `${HEADER}\n\nPayload.\n\n${END}`;
    const indented = region
      .split("\n")
      .map((line) => `    ${line}`)
      .join("\n");
    const nodes = markdownToSlate(
      `\`\`\`\`markdown\n${region}\n\`\`\`\`\n\n${indented}\n\n${region}\n`,
    );
    expect(nodes).toMatchObject([
      { type: "code-block" },
      { type: "code-block" },
      { type: "generated-region", status: "valid" },
    ]);
    expect(Node.string(nodes[0])).toBe(region);
    expect(Node.string(nodes[1])).toBe(region);
    expect(slateToMarkdown(nodes)).toContain(`${region}\n`);
  });

  it("allows prose after a terminal region without changing its original end-of-file bytes", () => {
    const source = `${HEADER}\n\nSaved payload.\n\n${END}`;
    const editor = withSchema(createEditor());
    editor.children = markdownToSlate(source);
    Editor.normalize(editor, { force: true });
    expect(slateToMarkdown(editor.children)).toBe(source);

    Transforms.select(editor, Editor.end(editor, []));
    Transforms.insertText(editor, "Handwritten after.");
    expect(slateToMarkdown(editor.children)).toBe(
      `${source}\n\nHandwritten after.\n`,
    );
  });
});
