//! MCP (Model Context Protocol) server over the vault API.
//!
//! `clep mcp` speaks MCP on stdio and proxies every tool call to the running
//! `clep serve` HTTP server, discovered through the same config lookup the
//! rest of the CLI uses. See docs/plans/2026-08-03-vault-mcp-server-and-skill.md
//! for the design and milestones.

pub mod client;
mod edit;
pub mod server;

use std::net::IpAddr;
use std::sync::Arc;

use rmcp::ServiceExt;

use crate::{ServerSettings, Settings, TlsSettings, default_tls_paths};
use client::ApiClient;
use server::VaultMcpServer;

/// True when `host` can only refer to this machine.
fn host_is_loopback(host: &str) -> bool {
    if host.eq_ignore_ascii_case("localhost") {
        return true;
    }
    host.trim_start_matches('[')
        .trim_end_matches(']')
        .parse::<IpAddr>()
        .is_ok_and(|ip| ip.is_loopback())
}

/// Build the HTTP base URL for the configured server.
///
/// Bind-all hosts (`0.0.0.0`, `::`) are unreachable as connect targets, so
/// they map to `localhost`; IPv6 literals are bracketed.
fn base_url(server: &ServerSettings) -> String {
    let scheme = if server.tls.enabled { "https" } else { "http" };
    let raw_host = server.host.as_str();
    let host = match raw_host {
        "0.0.0.0" | "::" | "[::]" => "localhost".to_string(),
        h if h.parse::<IpAddr>().is_ok_and(|ip| ip.is_ipv6()) => format!("[{h}]"),
        h => h.to_string(),
    };
    format!("{scheme}://{host}:{port}", port = server.port)
}

/// Load the server's TLS certificate for client-side trust, when TLS is on.
///
/// Returns `None` when the server runs plain HTTP. Errors when the cert pair
/// is half-configured or the certificate file does not exist yet (it is
/// generated by `clep serve` on first TLS startup).
fn load_tls_root_cert(tls: &TlsSettings) -> Result<Option<Vec<u8>>, Box<dyn std::error::Error>> {
    if !tls.enabled {
        return Ok(None);
    }
    let (cert_path, _key_path, _explicit) = default_tls_paths(tls)?
        .ok_or("could not determine the TLS certificate path (no app data directory)")?;
    let pem = std::fs::read(&cert_path).map_err(|e| {
        format!(
            "failed to read TLS certificate {}: {e}\n\
             hint: run `clep serve` once so it generates the local certificates",
            cert_path.display()
        )
    })?;
    Ok(Some(pem))
}

/// Run the MCP server on stdio until the client disconnects.
///
/// No tracing subscriber is installed here on purpose: stdout belongs to the
/// MCP protocol, and a default `fmt` subscriber would corrupt it.
pub async fn run_mcp(allow_remote: bool) -> Result<(), Box<dyn std::error::Error>> {
    let cwd = std::env::current_dir()?;
    let (settings, _config_path) = Settings::load(&cwd)?;

    if !host_is_loopback(&settings.server.host) && !allow_remote {
        return Err(format!(
            "refusing to target non-loopback server host \"{}\" — an MCP client would be \
             operating on a remote vault. Pass --allow-remote if that is intended.",
            settings.server.host
        )
        .into());
    }

    let base = base_url(&settings.server);
    let cert = load_tls_root_cert(&settings.server.tls)?;
    let client = ApiClient::new(base, cert)?;
    let mcp = VaultMcpServer::new(Arc::new(client));

    let service = mcp.serve(rmcp::transport::stdio()).await?;
    service.waiting().await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn server_settings(host: &str, port: u16, tls_enabled: bool) -> ServerSettings {
        ServerSettings {
            host: host.to_string(),
            port,
            dev_mode: false,
            tls: TlsSettings {
                enabled: tls_enabled,
                cert_path: None,
                key_path: None,
            },
        }
    }

    #[test]
    fn loopback_hosts_are_recognized() {
        for host in [
            "localhost",
            "LOCALHOST",
            "127.0.0.1",
            "127.1.2.3",
            "::1",
            "[::1]",
        ] {
            assert!(host_is_loopback(host), "{host} should be loopback");
        }
    }

    #[test]
    fn non_loopback_hosts_are_rejected() {
        for host in ["0.0.0.0", "::", "192.168.1.10", "vault.example.com"] {
            assert!(!host_is_loopback(host), "{host} should not be loopback");
        }
    }

    #[test]
    fn base_url_plain_http() {
        assert_eq!(
            base_url(&server_settings("localhost", 16667, false)),
            "http://localhost:16667"
        );
    }

    #[test]
    fn base_url_https_when_tls_enabled() {
        assert_eq!(
            base_url(&server_settings("127.0.0.1", 3000, true)),
            "https://127.0.0.1:3000"
        );
    }

    #[test]
    fn base_url_maps_bind_all_to_localhost() {
        assert_eq!(
            base_url(&server_settings("0.0.0.0", 8080, false)),
            "http://localhost:8080"
        );
        assert_eq!(
            base_url(&server_settings("::", 8080, false)),
            "http://localhost:8080"
        );
    }

    #[test]
    fn base_url_brackets_ipv6_literals() {
        assert_eq!(
            base_url(&server_settings("::1", 9000, false)),
            "http://[::1]:9000"
        );
    }

    #[test]
    fn tls_disabled_needs_no_cert() {
        let cert = load_tls_root_cert(&TlsSettings {
            enabled: false,
            cert_path: None,
            key_path: None,
        })
        .unwrap();
        assert!(cert.is_none());
    }

    /// The eval fixture (tests/mcp_evals/vault) must stay drift-free: its
    /// declared metadata already matches folder placement, so the serve-time
    /// reconcile sweep moves nothing and the checked-in answers in
    /// evaluation.xml stay valid. Runs over a copy — building the index
    /// writes a cache the checked-in tree must not accumulate.
    #[tokio::test]
    async fn eval_fixture_vault_is_drift_free() {
        let fixture =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/mcp_evals/vault");
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path().join("vault");
        copy_tree(&fixture, &root);

        let paths_before = markdown_paths(&root);
        assert_eq!(paths_before.len(), 10, "fixture should hold 10 pages");

        let state = crate::build_app_state(&root).await.unwrap();
        crate::run_startup_reconcile(&state).await;

        assert_eq!(
            markdown_paths(&root),
            paths_before,
            "reconcile moved fixture pages — evaluation.xml answers may now be stale"
        );
    }

    fn copy_tree(from: &std::path::Path, to: &std::path::Path) {
        std::fs::create_dir_all(to).unwrap();
        for entry in walkdir::WalkDir::new(from) {
            let entry = entry.unwrap();
            let dest = to.join(entry.path().strip_prefix(from).unwrap());
            if entry.file_type().is_dir() {
                std::fs::create_dir_all(&dest).unwrap();
            } else {
                std::fs::copy(entry.path(), &dest).unwrap();
            }
        }
    }

    fn markdown_paths(root: &std::path::Path) -> Vec<String> {
        let mut paths: Vec<String> = walkdir::WalkDir::new(root)
            .into_iter()
            .filter_map(Result::ok)
            .filter(|e| e.path().extension().is_some_and(|x| x == "md"))
            .map(|e| {
                e.path()
                    .strip_prefix(root)
                    .unwrap()
                    .to_string_lossy()
                    .into_owned()
            })
            .collect();
        paths.sort();
        paths
    }

    #[test]
    fn tls_enabled_with_missing_cert_file_hints_at_serve() {
        let tmp = tempfile::TempDir::new().unwrap();
        let err = load_tls_root_cert(&TlsSettings {
            enabled: true,
            cert_path: Some(tmp.path().join("missing.pem")),
            key_path: Some(tmp.path().join("missing-key.pem")),
        })
        .unwrap_err();
        assert!(err.to_string().contains("clep serve"), "{err}");
    }
}
