//! Uniform error handling for API responses.
use crate::vault::base_member::BaseMemberDiagnostic;
use crate::vault::path::VaultPath;
use axum::Json;
use axum::http::StatusCode;
use axum::response::{IntoResponse, Response};
use serde::Serialize;
use utoipa::ToSchema;

/// Uniform error payload for all API responses.
#[derive(Debug, Serialize, ToSchema)]
pub struct ApiError {
    pub status: u16,
    pub error: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hint: Option<String>,
}

/// Parse a path supplied directly by an API client.
///
/// Request validation failures are client errors and must not be used for
/// paths loaded from the index or generated by server-side code.
pub fn parse_request_path(path: &str, context: &str) -> Result<VaultPath, ApiError> {
    VaultPath::new(path).map_err(|error| ApiError::bad_request(format!("{context}: {error}")))
}

/// Parse a path that crossed an internal persistence or generation boundary.
///
/// A malformed internal path is a server invariant violation, not bad client
/// input, even when the original operation began with an API request.
pub fn parse_internal_path(path: &str, context: &str) -> Result<VaultPath, ApiError> {
    VaultPath::new(path).map_err(|error| ApiError::internal(format!("{context}: {error}")))
}

impl IntoResponse for ApiError {
    fn into_response(self) -> Response {
        let status = StatusCode::from_u16(self.status).unwrap_or(StatusCode::INTERNAL_SERVER_ERROR);
        (status, Json(self)).into_response()
    }
}

impl ApiError {
    pub fn not_found(msg: impl Into<String>) -> Self {
        Self {
            status: 404,
            error: msg.into(),
            detail: None,
            hint: None,
        }
    }

    pub fn conflict(msg: impl Into<String>) -> Self {
        Self {
            status: 409,
            error: msg.into(),
            detail: None,
            hint: None,
        }
    }

    pub fn conflict_with_detail(msg: impl Into<String>, detail: serde_json::Value) -> Self {
        Self {
            status: 409,
            error: msg.into(),
            detail: Some(detail),
            hint: None,
        }
    }

    pub fn revision_conflict(current_revision: String) -> Self {
        Self::conflict_with_detail(
            "page changed since it was loaded",
            serde_json::json!({
                "code": "revision_conflict",
                "current_revision": current_revision,
            }),
        )
    }

    pub fn bad_request(msg: impl Into<String>) -> Self {
        Self {
            status: 400,
            error: msg.into(),
            detail: None,
            hint: None,
        }
    }

    pub fn bad_request_with_detail(msg: impl Into<String>, detail: serde_json::Value) -> Self {
        Self {
            status: 400,
            error: msg.into(),
            detail: Some(detail),
            hint: None,
        }
    }

    pub fn invalid_embed_query(diagnostics: Vec<BaseMemberDiagnostic>) -> Self {
        Self::bad_request_with_detail(
            "invalid embed query",
            serde_json::json!({
                "code": "invalid_embed_query",
                "diagnostics": diagnostics,
            }),
        )
    }

    pub fn unprocessable_with_detail(msg: impl Into<String>, detail: serde_json::Value) -> Self {
        Self {
            status: 422,
            error: msg.into(),
            detail: Some(detail),
            hint: None,
        }
    }

    pub fn forbidden(msg: impl Into<String>) -> Self {
        Self {
            status: 403,
            error: msg.into(),
            detail: None,
            hint: None,
        }
    }

    pub fn internal(msg: impl Into<String>) -> Self {
        Self {
            status: 500,
            error: msg.into(),
            detail: None,
            hint: None,
        }
    }
}
