[package]
name = "clep-client"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
clep-config = { workspace = true }
reqwest = { workspace = true }
percent-encoding = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
clep-test-support = { workspace = true }
tokio = { workspace = true }
wiremock = { workspace = true }
serial_test = { workspace = true }
tempfile = { workspace = true }
url = { workspace = true }
