[package]
name = "clep-mcp"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
chrono = { workspace = true }
clep-client = { workspace = true }
clep-api = { workspace = true }
rmcp = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
axum = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
walkdir = { workspace = true }
